# Generated by Django 5.0.6 on 2024-07-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_APP', '0003_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
